### ISSUE TITLE
Baseline article template - missing site title "The Scenic"

### ISSUE THREAD

**Issue by spacedino** [ampproject/ampstart#335] opened 2017-03-15 00:21 UTC
- missing on mobile and desktop

![image](https://cloud.githubusercontent.com/assets/7339798/23928024/9c21784e-08da-11e7-8b4e-6dd896b6c52d.png)

**Comment by camelburrito** [comment] 2017-11-21 01:03
Dupe of https://github.com/ampproject/ampstart/issues/252

**Closed by camelburrito** 2017-11-21 01:03 UTC
