### ISSUE TITLE
[A11Y] Android: Some links on Get started page are not functional with talkback

### ISSUE THREAD

**Issue by gkhadke** [ampproject/ampstart#390] opened 2017-04-11 18:19 UTC
**ENVIRONMENT:**

OS (number): N (7.0)
Build number: NRD91R
Form factor (Smartphone / tablet):  Nexus 9
Browser: Chrome Dev 59.0.3062.4

**Pre-requisite:**
1. Talkback is ON

**STEPS TO REPRODUCE:**

1. Open [https://ampstart.com](https://ampstart.com)
2. Linearly Navigate to Sidebar Menu items and double tap on “Get Started” link
3. Linearly navigate to “Step 5: Test and publish page” or “Step 6: Provide feedback” section and  try to double tap on the links present in the respective steps.

**ACTUAL RESULTS:**

“Search Console’s AMP Test tool” link and “give us feedback” link are not clickable using double tap action.
Observation: Issue might be due to the focus issue caused by wrapping of links on the next line.

Note: With talkback off these links are clickable.

**EXPECTED RESULTS:**

All the identified links must be functional with talkback On.

**ATTACHMENT(S)**

[NonFunctionalLinks_GetStartedPage.mp4.zip](https://github.com/ampproject/ampstart/files/914304/NonFunctionalLinks_GetStartedPage.mp4.zip)

**Comment by torch2424** [comment] 2017-07-06 23:23
@camelburrito I could not reproduce this on my android device running talkback. Also, I don't seem to understand why it would have trouble clicking the link, as it is a simple <a href> within a <p> tag. Perhaps talkback updated and fixed the issue?

Currently, I feel that this issue can be closed

**Comment by torch2424** [comment] 2017-07-06 23:34
By @camelburrito approval, closing...

**Closed by torch2424** 2017-07-06 23:34 UTC
Labels: P2: Soon
